<footer>
    <h2 class="footer__header">HTML Bois</h2>
    <div class="footer__container">
        <section class="footer__card">
            <img src="./images/peter.png" alt="Peter Farmer's avatar">
            <div>
                <h3>Peter Farmer</h3>
                <a href="mailto:102573805@student.swin.edu.au">Email me !!</a>
            </div>
        </section>
        <section class="footer__card">
            <img src="./images/keath.png" alt="Keath Kor's avatar">
            <div>
                <h3>Keath Kor</h3>
                <a href="mailto:103844324@student.swin.edu.au">Email me !!</a>
            </div>
        </section>
        <section class="footer__card">
            <img src="./images/yongyuan.png" alt="Yong Yuan Chong's avatar">
            <div>
                <h3>Yong Yuan Chong</h3>
                <a href="mailto:101224021@student.swin.edu.au">Email me !!</a>
            </div>
        </section>
        <section class="footer__card">
            <img src="./images/quoc.png" alt="Kien Quoc Mai's avatar">
            <div>
                <h3>Kien Quoc Mai</h3>
                <a href="mailto:103532920@student.swin.edu.au">Email me !!</a>
            </div>
        </section>
        <section class="footer__card">
            <img src="./images/orson.png" alt="Orson Routt's avatar">
            <div>
                <h3>Orson Routt</h3>
                <a href="mailto:103575527@student.swin.edu.au">Email me !!</a>
            </div>
        </section>
    </div>
</footer>