<header id="header">
    <h1 class="logo">HB</h1>
    <nav>
        <div class="menu enhancement" id="intro-menu">
            <div class="menu__hamburger">
                <div></div>
                <div></div>
                <div></div>
            </div>
            <ul class="menu__list">
                <li><a id="index-page" href="index.html#index-page">Home</a></li>
                <li><a href="topic.html#topic-page">Topic</a></li>
                <li><a href="quiz.html#quiz-page">Quiz</a></li>
                <li><a href="enhancements.html#enhancement-page">Enhancements</a></li>
            </ul>
        </div>
    </nav>
</header>