<header id="header">
    <h1 class="logo">HB</h1>
    <nav>
        <div class="menu enhancement" id="intro-menu">
            <div class="menu__hamburger">
                <div></div>
                <div></div>
                <div></div>
            </div>
            <ul class="menu__list">
                <li><a id="index-page" href="index.php#index-page">Home</a></li>
                <li><a id="topic-page" href="topic.php#topic-page">Topic</a></li>
                <li><a id="quiz-page" href="quiz.php#quiz-page">Quiz</a></li>
                <li><a id="manage-page" href="login.php#manage-page">Manage</a></li>
                <li><a id="enhancement-page" href="enhancements.php#enhancement-page">Enhancements</a></li>
                <li><a id="phpenhancement-page" href="phpenhancements.php#phpenhancement-page">PHP-Enhancements</a></li>
            </ul>
        </div>
    </nav>
</header>